"""initial schema

Revision ID: 2410ff0060f7
Revises: 
Create Date: 2026-08-28 18:08:40.180105
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import Text  # автоген ссылается на Text(), но импорт не пишет
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '2410ff0060f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_telegram_id'), 'owners', ['telegram_id'], unique=True)
    op.create_table('rate_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('cbr_date', sa.String(length=32), nullable=True),
    sa.Column('cbr', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('market', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('calc_version', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('drom_url', sa.Text(), nullable=True),
    sa.Column('lot_number', sa.String(length=64), nullable=True),
    sa.Column('auction_name', sa.String(length=128), nullable=True),
    sa.Column('auction_date', sa.Date(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('make', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=96), nullable=True),
    sa.Column('trim', sa.String(length=128), nullable=True),
    sa.Column('generation', sa.String(length=96), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('month', sa.SmallInteger(), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=24), nullable=True),
    sa.Column('drive', sa.String(length=8), nullable=True),
    sa.Column('transmission', sa.String(length=8), nullable=True),
    sa.Column('volume_cc', sa.Integer(), nullable=True),
    sa.Column('power_hp', sa.SmallInteger(), nullable=True),
    sa.Column('power_kw', sa.SmallInteger(), nullable=True),
    sa.Column('is_electric', sa.Boolean(), nullable=False),
    sa.Column('age_band', sa.String(length=8), nullable=True),
    sa.Column('sanctioned', sa.Boolean(), nullable=False),
    sa.Column('fuel', sa.String(length=16), nullable=True),
    sa.Column('auction_grade', sa.String(length=8), nullable=True),
    sa.Column('interior_grade', sa.String(length=4), nullable=True),
    sa.Column('color', sa.String(length=48), nullable=True),
    sa.Column('doors', sa.SmallInteger(), nullable=True),
    sa.Column('seats', sa.SmallInteger(), nullable=True),
    sa.Column('vin', sa.String(length=32), nullable=True),
    sa.Column('plate_no', sa.String(length=32), nullable=True),
    sa.Column('price_foreign', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('price_rub_total', sa.BigInteger(), nullable=True),
    sa.Column('util_fee', sa.BigInteger(), nullable=True),
    sa.Column('util_preferential', sa.Boolean(), nullable=True),
    sa.Column('util_threshold_hp', sa.SmallInteger(), nullable=True),
    sa.Column('duty', sa.BigInteger(), nullable=True),
    sa.Column('customs_total', sa.BigInteger(), nullable=True),
    sa.Column('commission', sa.BigInteger(), nullable=True),
    sa.Column('commission_individual', sa.Boolean(), nullable=True),
    sa.Column('logistics_rf', sa.BigInteger(), nullable=True),
    sa.Column('logistics_city', sa.String(length=96), nullable=True),
    sa.Column('calc_input', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('calc_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('rates_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('rate_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('specs', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('extraction', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('description_ru', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['rate_snapshot_id'], ['rate_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cars_body_drive_tr', 'cars', ['owner_id', 'status', 'body', 'drive', 'transmission'], unique=False)
    op.create_index('ix_cars_country', 'cars', ['owner_id', 'status', 'country'], unique=False)
    op.create_index('ix_cars_mileage', 'cars', ['owner_id', 'status', 'mileage_km'], unique=False)
    op.create_index('ix_cars_owner_status', 'cars', ['owner_id', 'status'], unique=False)
    op.create_index('ix_cars_power', 'cars', ['owner_id', 'status', 'power_hp'], unique=False)
    op.create_index('ix_cars_price', 'cars', ['owner_id', 'status', 'price_rub_total'], unique=False)
    op.create_index('ix_cars_utilpref', 'cars', ['owner_id', 'status', 'util_preferential'], unique=False)
    op.create_index('ix_cars_year', 'cars', ['owner_id', 'status', 'year'], unique=False)
    op.create_table('ai_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime', sa.String(length=32), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('publio_file_id', sa.Text(), nullable=True),
    sa.Column('publio_file_id_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id', 'sha256', name='uq_car_photo_sha')
    )
    op.create_index('ix_photos_car', 'car_photos', ['car_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_photos_car', table_name='car_photos')
    op.drop_table('car_photos')
    op.drop_table('ai_calls')
    op.drop_index('ix_cars_year', table_name='cars')
    op.drop_index('ix_cars_utilpref', table_name='cars')
    op.drop_index('ix_cars_price', table_name='cars')
    op.drop_index('ix_cars_power', table_name='cars')
    op.drop_index('ix_cars_owner_status', table_name='cars')
    op.drop_index('ix_cars_mileage', table_name='cars')
    op.drop_index('ix_cars_country', table_name='cars')
    op.drop_index('ix_cars_body_drive_tr', table_name='cars')
    op.drop_table('cars')
    op.drop_table('rate_snapshots')
    op.drop_index(op.f('ix_owners_telegram_id'), table_name='owners')
    op.drop_table('owners')
    # ### end Alembic commands ###
