"""валютные суммы до перевода в рубли

Revision ID: adcec81ea85a
Revises: 2410ff0060f7
Create Date: 2026-09-03 11:34:38.596132
"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = 'adcec81ea85a'
down_revision: Union[str, None] = '2410ff0060f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('delivery_foreign', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('cars', sa.Column('foreign_total', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('cars', sa.Column('duty_eur', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('cars', sa.Column('duty_eur_per_cc', sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column('cars', sa.Column('customs_value_eur', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('cars', sa.Column('excise_units', sa.Numeric(precision=10, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'excise_units')
    op.drop_column('cars', 'customs_value_eur')
    op.drop_column('cars', 'duty_eur_per_cc')
    op.drop_column('cars', 'duty_eur')
    op.drop_column('cars', 'foreign_total')
    op.drop_column('cars', 'delivery_foreign')
    # ### end Alembic commands ###
